### ISSUE TITLE
Cannot sync.

### ISSUE THREAD

**Issue by nickavem** [rcdailey/recyclarr#62] opened 2022-05-12 22:43 UTC
Fedora 36 aarch64

```
[username@fedora ~]$ ./trash radarr -d
[INF] Processing Quality Definition: Movie
[DBG] HTTP Request to https://raw.githubusercontent.com/TRaSH-/Guides/master/docs/Radarr/Radarr-Quality-Settings-File-Size.md
[DBG] HTTP Response 200 from https://raw.githubusercontent.com/TRaSH-/Guides/master/docs/Radarr/Radarr-Quality-Settings-File-Size.md
[DBG] HTTP Request to http://hostname:7878/api/v3/qualitydefinition?apikey=SNIP
[DBG] HTTP Response 200 from http://hostname:7878/api/v3/qualitydefinition?apikey=SNIP
[DBG] HTTP Request to http://hostname:7878/api/v3/qualityDefinition/update?apikey=SNIP
[DBG] HTTP Response 202 from http://hostname:7878/api/v3/qualityDefinition/update?apikey=SNIP
[INF] Number of updated qualities: 0
[DBG] Custom format cache does not exist; proceeding without it
[ERR] An exception occurred during git operations on path: /var/home/username/.config/trash-updater/repo
LibGit2Sharp.LibGit2SharpException: could not load ssl libraries
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result) in /_/LibGit2Sharp/Core/Ensure.cs:line 154
   at LibGit2Sharp.Core.Ensure.ZeroResult(Int32 result) in /_/LibGit2Sharp/Core/Ensure.cs:line 172
   at LibGit2Sharp.Core.Proxy.git_clone(String url, String workdir, GitCloneOptions& opts) in /_/LibGit2Sharp/Core/Proxy.cs:line 275
   at LibGit2Sharp.Repository.Clone(String sourceUrl, String workdirPath, CloneOptions options) in /_/LibGit2Sharp/Repository.cs:line 793
   at VersionControl.Wrappers.LibGit2SharpRepositoryStaticWrapper.Clone(String sourceUrl, String workdirPath, CloneOptions options) in D:\a\trash-updater\trash-updater\src\VersionControl\Wrappers\LibGit2SharpRepositoryStaticWrapper.cs:line 8
   at VersionControl.GitRepositoryFactory.DeleteAndCloneRepo(String repoUrl, String repoPath, String branch) in D:\a\trash-updater\trash-updater\src\VersionControl\GitRepositoryFactory.cs:line 42
   at VersionControl.GitRepositoryFactory.CreateAndCloneIfNeeded(String repoUrl, String repoPath, String branch) in D:\a\trash-updater\trash-updater\src\VersionControl\GitRepositoryFactory.cs:line 27
   at TrashLib.Radarr.CustomFormat.Guide.LocalRepoCustomFormatJsonParser.CheckoutAndUpdateRepo() in D:\a\trash-updater\trash-updater\src\TrashLib\Radarr\CustomFormat\Guide\LocalRepoCustomFormatJsonParser.cs:line 68
[INF] Deleting local git repo and retrying git operation...
Segmentation fault (core dumped)
```

**Comment by rcdailey** [comment] 2022-05-12 23:24
Duplicate of #54. See [this wiki page](https://github.com/rcdailey/recyclarr/wiki/Troubleshooting#errors--solutions) for the solution.

**Closed by rcdailey** 2022-05-12 23:24 UTC
